"""Add password field to User model

Revision ID: 26060f081603
Revises: d84523cc9891
Create Date: 2025-09-21 13:01:23.412656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26060f081603'
down_revision = 'd84523cc9891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
